### ISSUE TITLE
weird bug: error handlig in express was no longer working

### ISSUE THREAD

**Issue by SharpBCD** [etienne-martin/device-detector-js#107]
Super weird bug... my error throwing was not working anymore only in the authentication module. Killed my self to understand why until I commented every line of extra code and pinpointed the error on device-detector-js.

Do you have some error handler that is missing an `next()` or something similar?

**Comment by etienne-martin** [comment]
Weird indeed. This library is just plain vanilla javascript, it's not tied to any http framework like express so I suspect you might have something weird going on in your code like a circular dependency or something.

If you can provide a reproduction and reopen the issue, I'll happily look into it.

**Comment by SharpBCD** [comment]
After I commented the device-detector, everything went smoothly so not sure about having something like circular reference or similar.
