### ISSUE TITLE
Incorrect iPhone models for mobile user agents

### ISSUE THREAD

**Issue by bannavaj** [etienne-martin/device-detector-js#117]
⚠️ Missing/incorrect detections should be reported at https://github.com/matomo-org/device-detector/issues instead of this repo.

Tried to report at the above attached link. Posting here too as not sure if the package handles parsing mobile app based user agents.

Mobile app device model version seems to be incorrect for the below and similar app based user agents. iPhone12 reports device as `iPhone 11 Pro` Max and just `iPhone` respectively.

- [ ] Testapp/2.148.2 (com.testapp.omega; build:20210204501; iPhone12,5; iOS 14.2; scale:3.0)
- [ ] Testapp/2.149.3 (com.testapp.omega; build:20210204501; iPhone13,5; iOS 14.2; scale:3.0)

**Comment by Findus23** [comment]
Hi,

That seems correct.

iPhone12,5 is the iPhone 11 Pro Max and the
iPhone 13,5 has not yet been released (the newest one is the `iPhone13,4`/`iPhone 12 Pro Max`).

Don't expect internal device names to be the same as the brand name: https://www.theiphonewiki.com/wiki/Models
