### ISSUE TITLE
How can I use to detect device on website access?

### ISSUE THREAD

**Issue by haizen007** [etienne-martin/device-detector-js#145]
I want to detect the phone model and OS of every mobile access to a website.
How can I use this lib for that?
Thanks

**Comment by etienne-martin** [comment]
Hi there, I would first check [the documentation](https://github.com/etienne-martin/device-detector-js#usage) or ask people over on StackOverflow for help. 

Let me know if the documentation could be improved.

**Comment by yCodeTech** [comment]
I vote to reopen this issue. The documentation is a little bit sparse. With only 1 example, albeit a poor example for the user agent detection:
````js
import DeviceDetector from "device-detector-js";

const deviceDetector = new DeviceDetector();
const userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36";
const device = deviceDetector.parse(userAgent);

console.log(device);
````

Typically, nobody would manually type in a userAgent string like that, it would be done via `window.navigator.userAgent` or other means (I'm not sure if there are other ways). Also, we shouldn't technically have to feed in the useragent ourselves, this should be detected and handled automatically by the library. However, that's by the by. What the documentation really needs is specifying whether it has any methods or ways to tell us what type of device it is. Like `isMobile` or `isDesktop`, or `isTablet`, just like there is in the php library. There is no reasonable way to deduce that the methods are exactly the same as in the php library.
