### ISSUE TITLE
Remove nodejs dependencies / add browser support

### ISSUE THREAD

**Issue by AlexBeauchemin** [etienne-martin/device-detector-js#18]
Would be nice to be able to use this lib without node
Would probably need to read and transform the yaml on build or post-install instead of fs.read it

https://github.com/etienne-martin/device-detector-js/blob/master/src/utils/yaml-loader.ts#L7

**Comment by etienne-martin** [comment]
Yes, it would be a good addition to lib. I thought the regex would be too heavy but they weigh about 250kb, even less when gzipped. We can definitely send that over the wire.

**Comment by etienne-martin** [comment]
We would also need to change the way the cache is implemented, maybe fallback to localstorage on the front end.

**Comment by etienne-martin** [comment]
We can maybe use [require-yml](https://www.npmjs.com/package/require-yml) to replace `fs.read` by bundling the yaml files directly in the bundle.

**Comment by etienne-martin** [comment]
We would also need to migrate to webpack.

**Comment by etienne-martin** [comment]
So `fs.read` was removed, the next step is to replace `lru-cache` with something that works in both the browser and node.

After that I need to find a way to make lodash treeshakable.

**Comment by AlexBeauchemin** [comment]
For lodash, that might do it
https://github.com/etienne-martin/device-detector-js/pull/20

**Comment by AlexBeauchemin** [comment]
For the cache, an easier solution might be to only skip the cache when running in the browser, because it will mostly be used by the client to validate his own user agent, so we don't really need to cache the results
https://github.com/etienne-martin/device-detector-js/pull/21

**Comment by etienne-martin** [comment]
Thanks 🙌
