### ISSUE TITLE
How to import library?

### ISSUE THREAD

**Issue by pqr** [etienne-martin/device-detector-js#29]
How to import the library into my typescript code?

1) When I write
```
import DeviceDetector from 'device-detector-js';
```
I get an error "no default export".

2) When I try
```
import * as DeviceDetector from 'device-detector-js';
```
It also shows an error and does not work.

3) Third attempt:
```
import { DeviceDetector }  from 'device-detector-js';
```
Error: there is no exported member "DeviceDetector"

Example in README.md shows require syntax, but I want to use ES6 modules syntax.
Could you please and an example with ES6 modules syntax into README.md?

**Comment by etienne-martin** [comment]
Hi there,

You need to use the CommonJS-style import syntax to use this module with typescript:

```typescript
import DeviceDetector = require("device-detector-js");
```

I will update the README with instruction on how to use this module with typescript.

Thanks for the feedback.
