### ISSUE TITLE
Caching is not working

### ISSUE THREAD

**Issue by arvinv** [etienne-martin/device-detector-js#30]
Hey Etienne,

This is Arvin again. We were testing the caching aspect of the device detection.  I don't think its working. We tried console.log of the cached result, its always empty even when the cache option is set to several minutes.

**Comment by etienne-martin** [comment]
Are you testing it in the browser or in node? Also could you show me what user agents are failing?

Note that caching is disabled in the browser.

**Comment by etienne-martin** [comment]
Also can you show me the code that fails?
