### ISSUE TITLE
[BUG] app is crashing on mac os safari

### ISSUE THREAD

**Issue by bartoszboruta** [etienne-martin/device-detector-js#31]
Hi, it seems like you didn't test it correctly!!!
My userAgent: 

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15`

![image](https://user-images.githubusercontent.com/17254885/51257132-42a73d00-19a7-11e9-9f86-63d7431068ff.png)

**Comment by etienne-martin** [comment]
You're right, it crashes in Safari.

Here's a repro:
https://codesandbox.io/s/kx7znjkynv

**Comment by etienne-martin** [comment]
He's a potential solution: https://stackoverflow.com/a/51568859/1123556

**Comment by mehmetnyarar** [comment]
I have the same problem and I depend on Safari. Is there a quick solution for this or when could you fix?

**Comment by andrejunges** [comment]
any news @mehmetnyarar @etienne-martin ?

**Comment by Logatto** [comment]
Hello, @etienne-martin @mehmetnyarar @andrejunges 
My temporal solution was add a try catch in userAgentParser, and this work in Safari and Firefox in MacOS.

I don't know what do you think about that.

**Comment by linhnguyen222** [comment]
This can be solved by update node to the lastest version

**Comment by etienne-martin** [comment]
This is fixed in [v2](https://www.npmjs.com/package/device-detector-js/v/2.0.0)
