### ISSUE TITLE
User Agent detection works in Matomo but bot Device Detector JS

### ISSUE THREAD

**Issue by brightq** [etienne-martin/device-detector-js#33]
Hey Etienne,

While using and testing this package, we have found some User agent get detected in devicedetector.net but not with device detector js. seems like mobiles.json needs to update to latest version to match the matomo mobiles.yml file

eg:
`Mozilla/5.0 (Linux; Android 8.0.0; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36`

device detected in: 
http://devicedetector.net/?ua=Mozilla%2F5.0+%28Linux%3B+Android+8.0.0%3B+ANE-LX1%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F71.0.3578.99+Mobile+Safari%2F537.36%09Mozilla%2F5.0+%28Linux%3B+Android+8.0.0%3B+LM-G710%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F71.0.3578.99+Mobile+Safari%2F537.36

but not in https://lx3rzx16x9.codesandbox.io/

**Comment by etienne-martin** [comment]
The javascript version (1.1.0) is now up-to-date with the php version (3.11.4).
