### ISSUE TITLE
Fail to detect Opera Mini Browser

### ISSUE THREAD

**Issue by linhnguyen222** [etienne-martin/device-detector-js#41]
The module does not work correctly on Opera Mini mobile
Tested on mobile Opera Mini
It returns 
{"client":{"type":"browser","name":"Mobile Safari","version":"","engine":"WebKit","engineVersion":"605.1"},"os":{"name":"iOS","version":"12.2","platform":""},"device":{"type":"smartphone","brand":"Apple","model":"iPhone"},"bot":null}
So basically the module detects this is Safari Mobile instead of Safari

https://gist.github.com/ireade/10fe4b3c1e1caa9751a3 <= this might help detect Opera Mini

**Comment by etienne-martin** [comment]
Please report missing/incorrect detections at https://github.com/matomo-org/device-detector/issues
