### ISSUE TITLE
Errors prompted when using webpack build

### ISSUE THREAD

**Issue by dylan-7** [etienne-martin/device-detector-js#45]
Error prompted when using webpack build. My version of webpack is 3.10.0, and typescript is 3.5.0
The content of the prompt:
Failed to compile.
Failed to minimize the bundle. Error: static/js/common.3.0.0.9 aad8.js from Uglify Js
Invalid assignment [static/js/common.3.0.0.9aad8.js:30539,48]
...

**Comment by etienne-martin** [comment]
Can you provide me with a way to reproduce the error please?

**Comment by dylan-7** [comment]
> Can you provide me with a way to reproduce the error please?

I use the version of webpack 3.0, webpack.config. js configures the uglifyJsPlugin plug-in to compress code and throw errors.
You can install the version of webpack 3.0, configure the following code, and try to build.

webpack.config.js:
```
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        comparisons: false,
      },
      mangle: {
        safari10: true,
      },
      output: {
        comments: false,
        ascii_only: true,
      },
    }),
```

**Comment by etienne-martin** [comment]
And the error only occurs when bundling `device-detector-js`?

**Comment by dylan-7** [comment]
> And the error only occurs when bundling `device-detector-js`?

I know the reason for the error, because your code uses ES6 grammar, and tsconfig.js is configured with "target": "es2017", and regular use ?<!, ?<! will throw errors in browsers such as safari, IE, edge, etc.

**Comment by etienne-martin** [comment]
Good find, I will try to lower the target in the next version.
