### ISSUE TITLE
Fixtures directory removed on updating

### ISSUE THREAD

**Issue by whimsicaldreamer** [etienne-martin/device-detector-js#66]
On running `yarn fixtures` the directory gets removed and is not recreated. Thus tests throws errors.

Dev Environment: Windows 10

**Comment by whimsicaldreamer** [comment]
I had to edit this line  
`destination = destination.replace("node_modules/device-detector", "fixtures");`  
to  
`destination = destination.replace("node_modules\\device-detector", "fixtures");`  
in **load-fixtures.js** to get it working.  

Am thinking of doing a PR with the updated version of the library and with this fix. Let me know if I am on the correct track.  

BTW, some tests are failing with the yandex browser with difference in version number. Not sure how to fix that.

**Comment by etienne-martin** [comment]
Looks like the backslash thingy fixed the issue for you on windows but broke it for me on mac 😕

**Comment by etienne-martin** [comment]
Fixed it in: https://github.com/etienne-martin/device-detector-js/pull/76

Let me know if that still works for you.

**Comment by whimsicaldreamer** [comment]
Yep it does fixes the issue. Sorry for the trouble. 😞

**Comment by etienne-martin** [comment]
All good, thanks for the fix

**Comment by whimsicaldreamer** [comment]
😄 You are welcome.. Will keep watching on this great lib..
