### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by whimsicaldreamer** [etienne-martin/device-detector-js#67]
Following the steps to update the library, certain tests fail. Not sure how to fix them.  
The failing tests are with the **yandex browser** only.  

![2](https://user-images.githubusercontent.com/8104493/71979308-66f8cb00-3243-11ea-9321-5d26e5fe4169.png)
![3](https://user-images.githubusercontent.com/8104493/71979316-6b24e880-3243-11ea-8707-893194c15ea6.png)
![1](https://user-images.githubusercontent.com/8104493/71979326-6f510600-3243-11ea-97bf-644633976c90.png)

**Comment by etienne-martin** [comment]
It looks like there may be an issue with [version truncation](https://github.com/etienne-martin/device-detector-js/blob/0fe281df53cd9464193bd4262c257841cba36a53/src/utils/version.ts#L3). 

It's probably caused by the trailing space in the version string.

You could try to trim that space in the version util and add a test case for that.

**Comment by whimsicaldreamer** [comment]
Could you guide me on how to add the tests as I am not comfortable with unit testing. 😞

**Comment by etienne-martin** [comment]
Sure, you just need to add a new test case in the following file: https://github.com/etienne-martin/device-detector-js/blob/0fe281df53cd9464193bd4262c257841cba36a53/src/tests/utils.test.ts after line 30.

Something like:
```typescript
expect(formatVersion("14.12.2125.9740.01 ", 1)).toEqual("14.12");
expect(formatVersion(" 14.12.2125.9740.01", 1)).toEqual("14.12");
expect(formatVersion(" 14.12.2125.9740.01 ", 1)).toEqual("14.12");
```

**Comment by whimsicaldreamer** [comment]
@etienne-martin, I am suspecting the issue occurs when fixtures are downloaded. Since the original library doesn't have trailing spaces in version string for yandex.

**Comment by etienne-martin** [comment]
You mean matomo-device-detector doesn't have trailing spaces in their yml files? If that's the case something's wrong with the conversion of the fixtures from yml to json.

**Comment by whimsicaldreamer** [comment]
@etienne-martin yes matomo device detector doesn't have trailing spaces in their yml files. I will dig through the original yml files again and find the exact cases to see if they have the spaces.

**Comment by whimsicaldreamer** [comment]
@etienne-martin I checked our converted json files to see if they have trailing spaces but it turns out that they don't. Something is going wrong somewhere. 😕 

![Annotation 2020-01-09 100245](https://user-images.githubusercontent.com/8104493/72038447-686bd700-32c7-11ea-8aa9-5ae34212a5d4.png)

**Comment by whimsicaldreamer** [comment]
Fixed the tests using the trim utility for now.  

![Annotation 2020-01-09 103254](https://user-images.githubusercontent.com/8104493/72039561-9f43ec00-32cb-11ea-9168-f198d8b83735.png)

**Comment by etienne-martin** [comment]
Good news, feel free to open a PR with your changes

**Comment by whimsicaldreamer** [comment]
@etienne-martin done. Take a look here: https://github.com/etienne-martin/device-detector-js/pull/68

Let me know if the changes are ok.

**Comment by etienne-martin** [comment]
Looks like there is a small issue I need to take care of regarding the CI. 

I will publish the new version to npm once it's fixed. 

Thanks for your contribution

**Comment by whimsicaldreamer** [comment]
Sounds great.
And you are welcome. 😄
