### ISSUE TITLE
Optimization: cache RegExp instances

### ISSUE THREAD

**Issue by yard** [etienne-martin/device-detector-js#71]
We found out that a simple change to ```user-agent.ts``` file could provide a significant speedup: full.test.ts completes in 10 seconds instead of 19 on our machines.

While this is not significant in browser scenario, it becomes really important in server-side setting (i.e. we saw an increase of several ms on our servers after integrating the library).

We are happy to submit a pull request with the changes that are currently sitting in our fork: https://github.com/lunalabsltd/device-detector-js/commit/2dd6a99c88d9e9910fd559181a68740d195111e3

**Comment by etienne-martin** [comment]
Good find, I incorporated your proposition in the PR I was working on: https://github.com/etienne-martin/device-detector-js/pull/72/files

**Comment by etienne-martin** [comment]
Note that with this approach, the cache is in memory so the it won't be shared between multiple instances of your application.

**Comment by etienne-martin** [comment]
The changes have been published to npm as [version 2.1.1](https://www.npmjs.com/package/device-detector-js/v/2.1.1)

Thanks for your contribution

**Comment by yard** [comment]
Thank for such a swift response! We will report new improvements as soon as we find them (I have a gut feeling we can make it even faster, current CPU consumption in our setup seems a bit higher than expected)

**Comment by etienne-martin** [comment]
A good way to troubleshoot performance issues would be to run a flamegraph profiler like [0x](https://www.npmjs.com/package/0x) on it to find the bottlenecks.
