### ISSUE TITLE
YAML Exception

### ISSUE THREAD

**Issue by whimsicaldreamer** [etienne-martin/device-detector-js#74]
Got the following error while running fixtures. Didn't get the time to debug, so thought of sharing.

![Annotation 2020-01-13 225435](https://user-images.githubusercontent.com/8104493/72278360-dca4d280-3659-11ea-9f5b-7c64c1e87395.png)

**Comment by etienne-martin** [comment]
I found the issue. There's a missing double quote at [line 1067](https://github.com/matomo-org/device-detector/blob/22257883bd2c7c21d68112a907cdad7de4a2ba31/Tests/Parser/fixtures/oss.yml#L1067) in a fixture file coming from matomo. We'll need to fix it upstream in their repo.

**Comment by etienne-martin** [comment]
https://github.com/matomo-org/device-detector/pull/6162

**Comment by whimsicaldreamer** [comment]
That's great!! Looks like we need to wait for things to get patched upstream.

**Comment by whimsicaldreamer** [comment]
@etienne-martin So how do you propose to fix it on our end?

**Comment by whimsicaldreamer** [comment]
Since, the issue is in oss.yml file, do you suggest manual download, conversion and editing?

**Comment by etienne-martin** [comment]
Yes exactly

**Comment by etienne-martin** [comment]
Ok I managed to pull the latest fixtures in this branch https://github.com/etienne-martin/device-detector-js/tree/3.12.3

You can use my branch to work on the latest version.

There are a couple of tests that needs to be fixed before we can merge that into master.

**Comment by whimsicaldreamer** [comment]
Great! I will check on the tests today.

**Comment by whimsicaldreamer** [comment]
First 2 tests were failing. Currently 1 fixed. 1 remaining.

![Annotation 2020-01-25 115636](https://user-images.githubusercontent.com/8104493/73117323-d4a63600-3f69-11ea-811e-06eda26286ad.png)

**Comment by whimsicaldreamer** [comment]
What would you advice for these errors? 

![Annotation 2020-01-25 133123](https://user-images.githubusercontent.com/8104493/73118204-0c67aa80-3f77-11ea-9a16-02843f0304f5.png)

**Comment by etienne-martin** [comment]
Great, the other ones might be a little bit tricky to fix. They seem to be related to this change: https://github.com/matomo-org/device-detector/commit/ce932a4c6a0de4587e293c08abafebc7db1e02bd#diff-3376e152ac4d378cf0bbf8d569e5213cR691

**Comment by whimsicaldreamer** [comment]
Hmm..So it looks like they have changed the way of detection. 🤔

**Comment by whimsicaldreamer** [comment]
@etienne-martin So do you think we need to change our core?

**Comment by etienne-martin** [comment]
Yeah they are using some kind of `getBrowserFamily` method that we don't have in the js version.

It's mapping certain browsers to a parent "Browser Family": https://github.com/matomo-org/device-detector/blob/ce932a4c6a0de4587e293c08abafebc7db1e02bd/Parser/Client/Browser.php#L274

**Comment by whimsicaldreamer** [comment]
Hmm. So we need to modify our https://github.com/etienne-martin/device-detector-js/blob/master/src/parsers/client/browser.ts

**Comment by whimsicaldreamer** [comment]
@etienne-martin https://github.com/whimsicaldreamer/device-detector-js/tree/core-update
Trying my luck with it.
