### ISSUE TITLE
Support on Internet Explorer

### ISSUE THREAD

**Issue by huynhkhai6678** [etienne-martin/device-detector-js#84]
⚠️ Missing/incorrect detections should be reported at https://github.com/matomo-org/device-detector/issues instead of in this repo.
I facing "Syntax error" on IE11.
The problem maybe arrow function (ES6 feature) not support on IE11
Demo link : https://lx3rzx16x9.codesandbox.io/ also crack on IE11.

**Comment by etienne-martin** [comment]
Hi there, unfortunately Internet Explorer is not supported.
