### ISSUE TITLE
How to use in browser

### ISSUE THREAD

**Issue by ddorian** [etienne-martin/device-detector-js#87]
For people that don't know npm/nodejs, how to use/build the package so I can import it as minified in a browser ?

**Comment by etienne-martin** [comment]
You can try using [browserify](http://browserify.org/) to create a minified bundle of the package.

**Comment by Findus23** [comment]
Just keep in mind that doing this browser-side means shipping somewhere around 432KB of Regex rules and 144KB of JS (uncompressed and not minified) which doesn't seem user-friendly to people on limited internet connections.

**Comment by etienne-martin** [comment]
Thanks you @Findus23 I updated the README with a disclaimer about that https://github.com/etienne-martin/device-detector-js#browser
