### ISSUE TITLE
not up2date

### ISSUE THREAD

**Issue by WuglyakBolgoink** [etienne-martin/device-detector-js#92]
current matomo detector has release v3.12.6

https://github.com/matomo-org/device-detector/releases/tag/3.12.6

can you do automated sync for regexes?

**Comment by whimsicaldreamer** [comment]
@WuglyakBolgoink updating the regexes only doesnt pass all tests. There is a PR already open for 3.12.5 but certain tests are failing.

**Comment by etienne-martin** [comment]
Thank you @WuglyakBolgoink I'm aware that the library is not up to date but I'm pretty swamped right now so I can't promise that I'm going to update it in the near future. 

As @whimsicaldreamer said, there is already [an open PR](https://github.com/etienne-martin/device-detector-js/pull/86) for that. You can maybe help with that, that would be appreciated.
