### ISSUE TITLE
How to use in old legacy project

### ISSUE THREAD

**Issue by WuglyakBolgoink** [etienne-martin/device-detector-js#93]
Hallo how can I use this module with my old project without typescript, ES6 Classes / Imports, webpack?

I have only this ES6 classes in this folders:
![image](https://user-images.githubusercontent.com/2271337/85425205-2f73a600-b579-11ea-9c7d-fbbf426a5288.png)

**Comment by etienne-martin** [comment]
It is not possible to use this project directly with legacy projects. You will need to manually transpile the code using babel or another transcompiler.
