### ISSUE TITLE
[bug with the JS implementation] device type and model is null in phone, but has value in computer

### ISSUE THREAD

**Issue by angelofan** [etienne-martin/device-detector-js#98]
Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1

Open https://lx3rzx16x9.codesandbox.io/ in phone:
```
"device":{
  "type":"",
  "brand":"Apple",
  "model":"",
}
```

Open https://lx3rzx16x9.codesandbox.io/ in pc, then copy the user agent above into the input:
```
"device":{
  "type":"smartphone",
  "brand":"Apple",
  "model":"iPhone",
}
```

Reply from Member of `device-detector` repository:
> Hi,
> 
> https://lx3rzx16x9.codesandbox.io/ uses https://github.com/etienne-martin/device-detector-js which is an implementation in JS that only shares the rules list.
> 
> The PHP version detects a "deviceName" of "smartphone":
> 
> https://devicedetector.lw1.at/Mozilla%2F5.0%20(iPhone;%20CPU%20iPhone%20OS%2014_0_1%20like%20Mac%20OS%20X)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F14.0%20Mobile%2F15E148%20Safari%2F604.1
> 
> In case this is a bug with the JS implementation, I'd recommend you to open an issue there.

See https://github.com/matomo-org/device-detector/issues/6067

**Comment by angelofan** [comment]
https://devicedetector.lw1.at/Mozilla%2F5.0%20(iPhone;%20CPU%20iPhone%20OS%2014_0_1%20like%20Mac%20OS%20X)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F14.0%20Mobile%2F15E148%20Safari%2F604.1


I opened this link on the mobile phone, the value of deviceName is smartphone, so this should be a bug implemented by js.

**Comment by etienne-martin** [comment]
This is not a bug in the js implementation but rather a compatibility issue with Safari.

You may experience inconsistencies when running this library in a browser environment, as some browsers like Safari do not yet support the lookbehind syntax for regexes.

The solution would be to run this library in a nodejs environment if you expect accurate results.

https://github.com/etienne-martin/device-detector-js#%EF%B8%8F-browser-environment

**Comment by angelofan** [comment]
Ok thanks for your clarification

My server uses lumen, it seems I have to integrate the device-detector into my server.
